name: Deploy to App Engine(Osaka)

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIP_TOKYO }}
          service_account: ${{ secrets.WIP_SRV_ACCOUNT_TOKYO }}

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v2'

      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.version_url }}"'
