name: Deploy to Cloud Run(Tokyo)

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v4'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIP_TOKYO }}
          service_account: ${{ secrets.WIP_SRV_ACCOUNT_TOKYO }}

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'nextjs'
          source: ./
          region: asia-northeast1

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
