name: Deploy to Cloud Run(Tokyo)

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v4'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIP_TOKYO }}
          service_account: ${{ secrets.WIP_SRV_ACCOUNT_TOKYO }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: asia-northeast1-docker.pkg.dev

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: asia-northeast1-docker.pkg.dev/nextjs-tokyo/nextjs/app:latest

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: nextjs
          image: asia-northeast1-docker.pkg.dev/nextjs-tokyo/nextjs/app:latest

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
